version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bookmark-backend
    expose:
      - "6005:6005"
    env_file:
      - ./backend/.env.prod
    networks:
      - bookmark-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bookmark-frontend
    expose:
      - "3002:3002"
    env_file:
      - ./frontend/.env.prod
    environment:
      INTERNAL_API_URL: http://backend:6005/api/v1
    depends_on:
      - backend
    networks:
      - bookmark-network
    restart: unless-stopped

networks:
  bookmark-network:
    driver: bridge
