"""Add reference field to bookmarks

Revision ID: 100ad4ecc52f
Revises: a754bcd3b880
Create Date: 2025-10-04 15:20:52.058293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100ad4ecc52f'
down_revision: Union[str, Sequence[str], None] = 'a754bcd3b880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('reference', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'reference')
    # ### end Alembic commands ###
