"""add is_private to bookmarks

Revision ID: 5dba7e3c0d0f
Revises: add_feedback_table
Create Date: 2026-05-30 15:41:01.560093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dba7e3c0d0f'
down_revision: Union[str, Sequence[str], None] = 'add_feedback_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'is_private')
    # ### end Alembic commands ###
