"""Describe the change

Revision ID: 2beacd71b5b3
Revises: add_follow_relationships
Create Date: 2026-02-08 15:03:46.344592

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bookmark_url_per_user"
down_revision: Union[str, Sequence[str], None] = "add_follow_relationships"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_bookmarks_search_vector", table_name="bookmarks", postgresql_using="gin"
    )
    op.drop_index("ix_bookmarks_url", table_name="bookmarks")
    op.create_index(op.f("ix_bookmarks_url"), "bookmarks", ["url"], unique=False)
    op.create_unique_constraint("uq_bookmark_url_user", "bookmarks", ["url", "user_id"])
    op.drop_constraint(
        "feed_articles_user_id_fkey", "feed_articles", type_="foreignkey"
    )
    op.create_foreign_key(None, "feed_articles", "users", ["user_id"], ["id"])
    op.drop_constraint(
        "user_preferences_user_id_key", "user_preferences", type_="unique"
    )
    op.drop_constraint(
        "user_preferences_user_id_fkey", "user_preferences", type_="foreignkey"
    )
    op.create_foreign_key(None, "user_preferences", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_preferences", type_="foreignkey")
    op.create_foreign_key(
        "user_preferences_user_id_fkey",
        "user_preferences",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "user_preferences_user_id_key", "user_preferences", ["user_id"]
    )
    op.drop_constraint(None, "feed_articles", type_="foreignkey")
    op.create_foreign_key(
        "feed_articles_user_id_fkey",
        "feed_articles",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_bookmark_url_user", "bookmarks", type_="unique")
    op.drop_index(op.f("ix_bookmarks_url"), table_name="bookmarks")
    op.create_index("ix_bookmarks_url", "bookmarks", ["url"], unique=True)
    op.create_index(
        "idx_bookmarks_search_vector",
        "bookmarks",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
