"""Add is_read field to bookmarks

Revision ID: a754bcd3b880
Revises: f1fbc58131d2
Create Date: 2025-10-02 19:12:18.144164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a754bcd3b880'
down_revision: Union[str, Sequence[str], None] = 'f1fbc58131d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('is_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'is_read')
    # ### end Alembic commands ###
