"""Add users table and user_id to bookmarks

Revision ID: e6cf35803d1e
Revises: 3b8d61a3a54e
Create Date: 2025-12-20 15:13:34.992376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6cf35803d1e'
down_revision: Union[str, Sequence[str], None] = '3b8d61a3a54e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.add_column('bookmarks', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('idx_bookmarks_created_at'), table_name='bookmarks')
    op.drop_index(op.f('idx_bookmarks_domain'), table_name='bookmarks')
    op.drop_index(op.f('idx_bookmarks_domain_created'), table_name='bookmarks')
    op.drop_index(op.f('idx_bookmarks_reference'), table_name='bookmarks')
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'bookmarks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.create_index(op.f('idx_bookmarks_reference'), 'bookmarks', ['reference'], unique=False)
    op.create_index(op.f('idx_bookmarks_domain_created'), 'bookmarks', ['domain', 'created_at'], unique=False)
    op.create_index(op.f('idx_bookmarks_domain'), 'bookmarks', ['domain'], unique=False)
    op.create_index(op.f('idx_bookmarks_created_at'), 'bookmarks', ['created_at'], unique=False)
    op.drop_column('bookmarks', 'user_id')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
